# Generated by Django 3.2 on 2021-05-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
