# Generated by Django 3.2.23 on 2024-08-31 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('inco_date', models.DateField(blank=True, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=16, null=True)),
                ('tan', models.CharField(blank=True, max_length=20, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('iec', models.CharField(blank=True, max_length=15, null=True)),
                ('income_tax_password', models.CharField(blank=True, max_length=30, null=True)),
                ('gst_userid', models.CharField(blank=True, max_length=30, null=True)),
                ('gst_password', models.CharField(blank=True, max_length=30, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ManyToManyField(to='contacts.Contact')),
                ('org_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.orgtype')),
            ],
        ),
    ]
